In [10]:
# importing files
import numpy as np
import pandas as pd
# if user makes mistake giving movie name then it will give closest match of the value
import difflib
# convert textual data into numerical values
from sklearn.feature_extraction.text import TfidfVectorizer
# find which movies have heighest similarity score
from sklearn.metrics.pairwise import cosine_similarity

In [11]:
# collecting data and preprocess
# loading the data
movies_data = pd.read_csv("movies.csv")

In [12]:
# printing first 5 rows
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [14]:
# finding number of rows and columns
movies_data.shape

(4803, 24)

In [24]:
# selecting relevant features for recommendation

selected_features = ['genres','keywords','tagline','cast','director','overview','original_language']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director', 'overview', 'original_language']


In [25]:
# replacing the missing values with null string

for feature in selected_features:
    movies_data[feature] = movies_data[feature].fillna('')

In [26]:
# combining all the 8 selected features

combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']+' '+movies_data['overview']+' '+movies_data['original_language']

In [27]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      A New Yorker in Shanghai Daniel Henney Eliza...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [29]:
# converting text data to feature vectors

vectorizer = TfidfVectorizer()

In [30]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [31]:
print(feature_vectors)

  (0, 8926)	0.02665578026167305
  (0, 5247)	0.16501006775547178
  (0, 1015)	0.12281483475578292
  (0, 1244)	0.052688384272339364
  (0, 21531)	0.16644197206569722
  (0, 1282)	0.03194056277386936
  (0, 19657)	0.16114836117475895
  (0, 10373)	0.1384336281545381
  (0, 2976)	0.09970589210080175
  (0, 27530)	0.14564049713224922
  (0, 2687)	0.09801861855221852
  (0, 4131)	0.06193539266210169
  (0, 18030)	0.10935524187822071
  (0, 28612)	0.15485255642963552
  (0, 19548)	0.04906580238586929
  (0, 18254)	0.1476456874519244
  (0, 27420)	0.03100401179862503
  (0, 7831)	0.17973500853712363
  (0, 14028)	0.04167600071036139
  (0, 17026)	0.143194506489404
  (0, 20111)	0.19253195938485537
  (0, 4770)	0.12497113327809026
  (0, 239)	0.197099388840671
  (0, 13479)	0.036465463446112366
  (0, 4290)	0.13208435165943985
  :	:
  (4802, 19250)	0.06134088052640477
  (4802, 11946)	0.07828093766187212
  (4802, 29695)	0.07734470758484706
  (4802, 9350)	0.07103332353189366
  (4802, 19490)	0.05756631608304895
  (4802

In [32]:
# using cosine similarity to get similarity score
#it will find similar values ie. similar movies

similarity = cosine_similarity(feature_vectors)

In [33]:
print(similarity)

[[1.         0.05148617 0.03392811 ... 0.02801039 0.03099337 0.00770394]
 [0.05148617 1.         0.04417805 ... 0.05125681 0.03149969 0.01564774]
 [0.03392811 0.04417805 1.         ... 0.02694306 0.04797411 0.01414021]
 ...
 [0.02801039 0.05125681 0.02694306 ... 1.         0.03518829 0.03579459]
 [0.03099337 0.03149969 0.04797411 ... 0.03518829 1.         0.03130853]
 [0.00770394 0.01564774 0.01414021 ... 0.03579459 0.03130853 1.        ]]


In [35]:
print(similarity.shape)

(4803, 4803)


In [36]:
# getting the movie name from the user
movie_name = input("Enter your Favourate Movie Name!")

Enter your Favourate Movie Name!hangover


In [37]:
# creating list of names of all the movies.
list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [38]:
# finding the close match for the movie name given by the user.
# taking the value given by the user and comparing it with all the values in the list.
find_close_match = difflib.get_close_matches(movie_name,list_of_all_titles)
print(find_close_match)

['The Hangover', 'Cliffhanger', 'Tango']


In [39]:
close_match = find_close_match[0]
print(close_match)

The Hangover


In [43]:
# finding the index of the movie with the title
index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

1356


In [45]:
# getting list of similar movies based by index of the movie
# to loop through the list we are using enumarate.
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.021927700041510956), (1, 0.04898872065779908), (2, 0.02470183564176388), (3, 0.026157735767696266), (4, 0.05160920017058321), (5, 0.0243293828053754), (6, 0.02658729286212188), (7, 0.048490634511709436), (8, 0.010278767987119863), (9, 0.016313970042880762), (10, 0.023518881104907026), (11, 0.03716786730265473), (12, 0.00893657553771514), (13, 0.0264796311207024), (14, 0.044582459273160235), (15, 0.04013565489320389), (16, 0.030451726215519163), (17, 0.034595681359211504), (18, 0.06789735554271988), (19, 0.05337112093462183), (20, 0.04417397921914026), (21, 0.025183071474480383), (22, 0.04255733623786341), (23, 0.021368775705034725), (24, 0.02830213072738031), (25, 0.039872039683010674), (26, 0.019992734339325094), (27, 0.04899757032796162), (28, 0.009613305501080952), (29, 0.04331125566774113), (30, 0.03855696301399173), (31, 0.01567504736659174), (32, 0.05193388817119582), (33, 0.016441724882821605), (34, 0.0523681935474992), (35, 0.017713849268158145), (36, 0.03853797800365958

In [46]:
len(similarity_score)

4803

In [47]:
# sort the movies based on higher similarity score
# reverse = true means descending order
#x:x[1] means x is similarity score and x[0] is the first element and second element is similarity value

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

[(1356, 0.9999999999999998), (427, 0.31517026515967844), (1712, 0.16021648070896913), (3048, 0.1389243351419), (923, 0.11881824974475587), (3425, 0.11494852859186525), (3580, 0.11489063734417627), (1328, 0.10945104070461237), (2833, 0.10786146057564529), (1222, 0.10643182032902351), (1048, 0.10540521021288989), (4696, 0.10499623251158686), (3056, 0.10414455301670338), (3255, 0.10340641425231453), (631, 0.1033422965630906), (2044, 0.10171727815194531), (78, 0.1011940534753527), (2329, 0.10073168945770418), (146, 0.10042993765696279), (1577, 0.09933070824052817), (2407, 0.09856404804682724), (1959, 0.09840653562363971), (641, 0.09831057962853493), (2862, 0.0979391273823759), (2160, 0.09684086594873553), (2392, 0.09652792826793569), (3171, 0.0962130477558364), (4062, 0.0960062721365676), (2181, 0.09588885288025809), (949, 0.0950333472236327), (2827, 0.09494795823684844), (911, 0.09464516692327163), (989, 0.09417333192295484), (2512, 0.09396779118430938), (2755, 0.09353735899976101), (1698

In [50]:
#print top 10 names of similar movies based on index

print("Top 10 movies suggested for you!")
i = 1
for movie in sorted_similar_movies:
    index = movie[0]
    # using the index value finding the title from the movies dataset
    title_from_index = movies_data[movies_data.index == index]['title'].values[0]
    if(i<11):
        print(i,'.',title_from_index)
        i+=1

Top 10 movies suggested for you!
1 . The Hangover
2 . The Hangover Part II
3 . Last Vegas
4 . Very Bad Things
5 . Failure to Launch
6 . Go
7 . Doug's 1st Movie
8 . The Town
9 . Johnson Family Vacation
10 . Sex Tape
